/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CityMap {
  schemaVersion?: string;
  projectId: string;
  root: string;
  generatedAt: string;
  stats: Stats;
  districts: District[];
  buildings: Building[];
  unresolved: Unresolved[];
  links: Link[];
}
export interface Stats {
  files: number;
  loc: number;
  links: number;
  unresolved: number;
  durationMs: number;
}
export interface District {
  id: string;
  parentId: string | null;
  path: string;
  depth: number;
  rect: Rect;
  y: number;
  fileCount: number;
  loc: number;
}
export interface Rect {
  x: number;
  z: number;
  w: number;
  d: number;
}
export interface Building {
  id: string;
  districtId: string;
  path: string;
  name: string;
  lang:
    | 'python'
    | 'typescript'
    | 'javascript'
    | 'java'
    | 'kotlin'
    | 'c'
    | 'cpp'
    | 'go'
    | 'rust'
    | 'csharp'
    | 'ruby'
    | 'php'
    | 'swift'
    | 'scala'
    | 'objectivec'
    | 'lua'
    | 'perl'
    | 'r'
    | 'erlang'
    | 'fortran'
    | 'solidity'
    | 'zig'
    | 'vue'
    | 'gdscript'
    | 'plsql'
    | 'smalltalk'
    | 'ttcn'
    | 'other';
  position: Point;
  footprint: Footprint;
  height: number;
  metrics: Metrics;
  grade: 'clean' | 'watch' | 'hot' | 'critical';
  floors?: Floor[];
}
export interface Point {
  x: number;
  z: number;
}
export interface Footprint {
  w: number;
  d: number;
}
export interface Metrics {
  loc: number;
  sloc: number;
  comments: number;
  symbols: number;
  functions: number;
  classes: number;
  maxCC: number;
  avgCC: number;
  ccDensity: number;
  fanIn: number;
  fanOut: number;
}
/**
 * One function, drawn as a slab of the building it lives in.
 *
 * `y` and `height` are computed server-side so the stack stays deterministic and testable
 * alongside the rest of the layout.
 */
export interface Floor {
  name: string;
  cc: number;
  line: number;
  grade: 'clean' | 'watch' | 'hot' | 'critical';
  y: number;
  height: number;
}
export interface Unresolved {
  from: string;
  spec: string;
  reason: 'external' | 'not_found' | 'unsupported';
}
export interface Link {
  id: string;
  source: string;
  target: string;
  kind: 'import';
  weight: number;
  bidirectional: boolean;
}
